name: insurance_inference_env
dependencies:
  - python=3.9
  - pip=23.2
  - cmake
  - ninja
  - llvm-openmp
  - pip:
      - azureml-sdk==1.59.0
      - azureml-defaults==1.59.0
      - azure-storage-blob
      - scikit-learn
      - joblib
      - inference-schema[numpy-support]
      - lightgbm==3.2.1
      - pandas==1.1.3
channels:
  - defaults
  - conda-forge